/* DDLs */

CREATE TABLE dimCITYS (
    USER_CITY_ID int IDENTITY(1,1) PRIMARY KEY,
    USER_CITY varchar(38) NOT NULL
);
CREATE TABLE dimOS (
    DEVICE_OS_ID int IDENTITY(1,1) PRIMARY KEY,
    DEVICE_OS varchar(38) NOT NULL
);
CREATE TABLE dimMOBILES (
    DEVICE_MOBILE_ID int IDENTITY(1,1) PRIMARY KEY,
    DEVICE_MOBILE varchar(38) NOT NULL
);
CREATE TABLE dimBROWSERS (
    DEVICE_BROWSER_ID int IDENTITY(1,1) PRIMARY KEY,
    DEVICE_BROWSER varchar(100) NOT NULL
);
CREATE TABLE dimSEGMENTS (
    SEGMENT_ID int NOT NULL PRIMARY KEY,
    SEGMENT_DESCRIPTION varchar(38) NOT NULL
);
CREATE TABLE dimEVENTS (
    EVENT_ID int NOT NULL PRIMARY KEY,
    EVENT_DESCRIPTION varchar(50) NOT NULL
);
CREATE TABLE USERS (
    USER_ID int NOT NULL PRIMARY KEY,
    SEGMENT_ID int,
    CONSTRAINT FK_SEGMENT_ID FOREIGN KEY (SEGMENT_ID) REFERENCES dimSEGMENTS(SEGMENT_ID)
);
CREATE TABLE SESSIONS (
    SESSION_ID int NOT NULL PRIMARY KEY,
    EVENT_ID int NOT NULL,
    USER_ID int NOT NULL,
    DEVICE_BROWSER_ID int,
    DEVICE_MOBILE_ID int,
    DEVICE_OS_ID int,
    USER_CITY_ID int,
    SERVER_TIME TIMESTAMP,
    TIME_SPENT int,
    CRASH_DETECTION varchar(100),
    CONSTRAINT FK_EVENT_ID FOREIGN KEY (EVENT_ID) REFERENCES dimEVENTS(EVENT_ID),
    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_DEVICE_BROWSER_ID FOREIGN KEY (DEVICE_BROWSER_ID) REFERENCES dimBROWSERS(DEVICE_BROWSER_ID),
    CONSTRAINT FK_DEVICE_MOBILE_ID FOREIGN KEY (DEVICE_MOBILE_ID) REFERENCES dimMOBILES(DEVICE_MOBILE_ID),
    CONSTRAINT FK_DEVICE_OS_ID FOREIGN KEY (DEVICE_OS_ID) REFERENCES dimOS(DEVICE_OS_ID),
    CONSTRAINT FK_USER_CITY_ID FOREIGN KEY (USER_CITY_ID) REFERENCES dimCITYS(USER_CITY_ID)
);